// app/layout.jsx
import SessionWrapper from "@/components/SessionWrapper";
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      {/* 👇 add this prop */}
      <body suppressHydrationWarning>
        <SessionWrapper session={session}>{children}</SessionWrapper>
      </body>
    </html>
  );
}
